export const CREATE_PROJECT = "CREATE_PROJECT";
export const RETRIEVE_PROJECTS = "RETRIEVE_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_ALL_PROJECTS = "DELETE_ALL_PROJECTS";
